<?php

namespace AppBundle\Repository;

/**
 * prodComRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class prodComRepository extends \Doctrine\ORM\EntityRepository
{

}
