<?php

namespace ProduitBundle\Repository;

/**
 * produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produitRepository extends \Doctrine\ORM\EntityRepository
{
   public function findOneByName($name)
   {
      return $this->createQueryBuilder('produit')
            ->where('produit.nomP LIKE :nomP')
            ->setParameter('nomP','%'.$name.'%')
            ->getQuery()
           ->getResult();
   }


}

